---
title: "BARBARIT"
format: html
---

```{r, message=FALSE, warning=FALSE}
here::i_am("lab-grades.Rproj")
library(here)
library(tidyr)
library(ggplot2)
library(dplyr)
library(vroom)
```

```{r, message=FALSE, warning=FALSE}
courses <- vroom(here("data","courses.csv"))
```


```{r, message=FALSE, warning=FALSE}
courses |>
  rename(
    "course name" = course,
    "identifier" = course_id,
    "module" = module,
    "number of exams" = nb_grades
  ) |>
  arrange(`course name`) |>
  knitr::kable()
```

```{r, message=FALSE, warning=FALSE}
students <- vroom(here("data","students.csv"),
                  col_types = cols(
                       id = col_integer(),
                       group = col_factor(),
                       birth_date = col_date(),
                       sex = col_factor()
                     ))
```

The birth_date column of the students data frame is of class `r class(students$birth_date)`

The sex column of the students data frame is of class `r class(students$sex)`


```{r, message=FALSE, warning=FALSE}
library(readr)

grades <- read_delim(here("Data", "grades.csv"),
  delim = "|",
  na = "*",
  col_types = cols(
    id = col_integer(),
    course_id = col_integer(),
    grade = col_double()
  )
)
```

```{r, message=FALSE, warning=FALSE}
students |> 
  group_by(group) |>
  summarise(n = n())|>
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  theme_minimal()+
  labs(title = "Number of Students per Group",
       y = "Count")
```

```{r, message=FALSE, warning=FALSE}
students |>
  group_by(group, sex) |>
  summarise(n = n(), .groups = "drop") |>
  ggplot(aes(x = group, y = n, fill = sex)) +
  geom_col(position = "fill") +
  labs(title = "Gender Balance per Group",
       y = "Proportion")
```

```{r, message=FALSE, warning=FALSE}
library(lubridate)

students |>
  mutate(age = round(time_length(today() - birth_date, unit="year"))) |>
  ggplot(aes(x = age)) +
  geom_histogram(bins = 20) +
  theme_minimal()+
  labs(title = "Distribution of Student Ages")
```

```{r, message=FALSE, warning=FALSE}
students |>
  mutate(age = round(time_length(today() - birth_date, "year"))) |>
  group_by(group) |>
  summarise(median_age = median(age))|>
  knitr::kable()
```

```{r, message=FALSE, warning=FALSE}
students |>
  mutate(age = round(time_length(today() - birth_date, "year"))) |>
  group_by(group) |>
  slice_max(age) |>
  ungroup() |>
  arrange(desc(age)) |>
  select(id, sex, age, group) |>
  knitr::kable()
```

```{r, message=FALSE, warning=FALSE}
n_grades <- grades |>
  filter(!is.na(grade)) |>
  nrow()
```

The data set contains `r n_grades` grades.

```{r,message=FALSE, warning=FALSE}
sword_id <- courses |>
  filter(course == "Swordsmanship and Martial Arts") |>
  pull(course_id)

grades |>
  filter(course_id == sword_id) |>
  left_join(students, by = "id") |>
  group_by(group) |>
  summarise(avg_grade = mean(grade, na.rm = TRUE)) |>
  ggplot(aes(x = group, y = avg_grade)) +
  geom_col() +
  theme_minimal()+
  labs(title = "Average Swordsmanship Grades per Group")
```

```{r, message=FALSE, warning=FALSE}
grades |>
  filter(!is.na(grade)) |>
  left_join(courses, by = "course_id") |>
  ggplot(aes(x = grade, fill = factor(module))) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1) +
  labs(fill = "Module",
       title = "Grade Distributions by Module")
```

```{r, message=FALSE, warning=FALSE}
grades_per_student <- grades |>
  filter(!is.na(grade)) |>
  group_by(id) |>
  summarise(`number of grades`=n()) |>
  left_join(students, by = "id")

grades_per_student |>
  slice_head(n = 5) |>
  knitr::kable()

grades_per_student |>
  summarise(
    `min nb of grades` = min(`number of grades`),
    `max nb of grades` = max(`number of grades`),
    `avg nb of grades` = round(mean(`number of grades`)),
    `median nb of grades` = median(`number of grades`)
  ) |>
  knitr::kable()
```

```{r, message=FALSE, warning=FALSE}
grades_per_student |>
  ggplot(aes(x = `number of grades`, fill = sex)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1) +
  labs(title = "Distribution of Number of Grades by Sex")+
  theme_minimal()+
  facet_wrap(~sex)
```

```{r, message=FALSE, warning=FALSE}
dragon_id <- courses |>
  filter(course == "Dragon Lore and Taming") |>
  pull(course_id)

dragon_grades <- grades |>
  filter(course_id == dragon_id) |>
  group_by(id) |>
  summarise(`number of grades in Dragon Lore and Taming`=n()) |>
  left_join(students, by = "id") |>
  select(id, group, `number of grades in Dragon Lore and Taming`)

dragon_grades |>
  slice_head(n = 5) |>
  knitr::kable()
```

```{r, message=FALSE, warning=FALSE}
dragon_grades |>
  group_by(`number of grades in Dragon Lore and Taming`) |>
  summarise(`number of students`=n()) |>
  ggplot(aes(x = `number of grades in Dragon Lore and Taming`, y = `number of students`)) +
  geom_col() +
  labs(title = "Number of Students by Count of Dragon Lore Grades")+
  theme_minimal()
```

